try{
    throw Error("oops");
    // console.log(b);
}catch(e){
    console.log(e.message);
}finally{
    
}